name = "GridSim"
uuid = "a29d37a4-ace7-4bbf-8eae-25e6952bdf36"
authors = ["arnaud-ma <arnaudma.code@gmail.com> and contributors"]
version = "1.0.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Colors = "0.12"
Random = "<0.0.1, 1"
julia = ">=1.8"
